issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - errcheck
        - dupl
    - path: testing/
      linters:
        - errcheck
        - dupl
    - path: tests/
      linters:
        - dupl
run:
  timeout: 5m
linters:
  enable:
    - asasalint
    - asciicheck
    - contextcheck
    - dupl
    - exportloopref
    - nilerr
