postgresql.connection = 'postgres://repl_user@localhost:5432/postgres'
postgresql.password = '...'
#postgresql.publication = 'replication_name'
#postgresql.snapshot.batchsize = 1000
#postgresql.snapshot.initial = 'always'

sink.type = 'nats'
sink.nats.address = 'nats://localhost:4222'
sink.nats.authorization = "userinfo"
sink.nats.userinfo.username = 'publisher'
sink.nats.userinfo.password = '...'

#sink.type = 'stdout'

#sink.type = 'kafka'
#sink.kafka.brokers = ['']
#sink.kafka.sasl.enabled = true
#sink.kafka.sasl.user = '$ConnectionString'
#sink.kafka.sasl.mechanism = 'PLAIN'
#sink.kafka.tls.enabled = true
#sink.kafka.tsl.skipverify = true
#sink.kafka.tsl.clientauth = 0

topic.namingstrategy.type = 'debezium'
topic.prefix = 'timescaledb'

timescaledb.hypertables.excludes = []
timescaledb.hypertables.includes = ['public.test']
timescaledb.events.read = true
timescaledb.events.insert = true
timescaledb.events.update = true
timescaledb.events.delete = true
timescaledb.events.truncate = true
timescaledb.events.compression = true
timescaledb.events.decompression = true
