postgresql.connection = 'postgres://repl_user@localhost:5432/postgres'
postgresql.password = '...'
#postgresql.publication = 'replication_name'
#postgresql.snapshot.batchsize = 1000
#postgresql.snapshot.initial = 'always'
#postgresql.transaction.window.enabled = true
#postgresql.transaction.window.timeout = 60
#postgresql.transaction.window.maxsize = 100000

sink.tombstone = false

sink.type = 'nats'
sink.nats.address = 'nats://localhost:4222'
sink.nats.authorization = "userinfo"
sink.nats.userinfo.username = 'publisher'
sink.nats.userinfo.password = '...'

#sink.type = 'stdout'

#sink.type = 'kafka'
#sink.kafka.brokers = ['']
#sink.kafka.sasl.enabled = true
#sink.kafka.sasl.user = '$ConnectionString'
#sink.kafka.sasl.mechanism = 'PLAIN'
#sink.kafka.tls.enabled = true
#sink.kafka.tsl.skipverify = true
#sink.kafka.tsl.clientauth = 0

#sink.redis.network = 'tcp'
#sink.redis.address = 'localhost:6379'
#sink.redis.password = ''
#sink.redis.database = 0
#sink.redis.poolsize = 0
#sink.redis.retries.maxattempts = 0
#sink.redis.retries.backoff.min = 8
#sink.redis.retries.backoff.max = 512
#sink.redis.timeouts.dial = 0
#sink.redis.timeouts.read = 0
#sink.redis.timeouts.write = 0
#sink.redis.timeouts.pool = 0
#sink.redis.timeouts.idle = 0
#sink.redis.tls.enabled = false
#sink.redis.tls.skipverify = false
#sink.redis.tls.clientauth = 0

topic.namingstrategy.type = 'debezium'
topic.prefix = 'timescaledb'

timescaledb.hypertables.excludes = []
timescaledb.hypertables.includes = ['public.test']
timescaledb.events.read = true
timescaledb.events.insert = true
timescaledb.events.update = true
timescaledb.events.delete = true
timescaledb.events.truncate = true
timescaledb.events.message = false
timescaledb.events.compression = false
timescaledb.events.decompression = false
