name: "Build / Lint / Tests"

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "**" ]

env:
  golang-version: 1.20.2
  golangci-lint-version: v1.51.2
  docker-registry: ghcr.io
  docker-image-name: ${{ github.repository }}

defaults:
  run:
    shell: bash --noprofile --norc -eo pipefail {0}

jobs:
  build:
    runs-on: ubuntu-latest
    name: "Building, Linting, Formatting"

    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: ${{ env.golang-version }}
      id: go

    - name: Lint
      uses: golangci/golangci-lint-action@v3
      with:
        version: ${{ env.golangci-lint-version }}

    - name: Format
      run: |
        make fmt
        git diff --exit-code .

    - name: Build
      run: make build

  test:
    strategy:
      matrix:
        pg_version: [13, 14, 15]

    name: Tests (Unit / Int) - PG ${{ matrix.pg_version }}
    runs-on: self-hosted
    steps:
    - name: Check out code into the Go module directory
      uses: actions/checkout@v3

    - name: Install colima on MacOS
      if: ${{ matrix.os == 'macos-latest' }}
      run: brew install colima docker && colima start

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: ${{ env.golang-version }}
      id: go

    - name: Test
      if: ${{ matrix.os != 'macos-latest' }}
      run: TSES_TEST_PG_VERSION=${{ matrix.pg_version }} make test > unit-run.log  2>&1

    - name: Test
      if: ${{ matrix.os == 'macos-latest' }}
      run: TSES_TEST_PG_VERSION=${{ matrix.pg_version }} make test > unit-run.log  2>&1
      env:
        DOCKER_HOST: 'unix:///Users/runner/.colima/default/docker.sock'
        TESTCONTAINERS_DOCKER_SOCKET_OVERRIDE: '/var/run/docker.sock'

    - name: 'Print failure logs'
      if: ${{ failure() }}
      run: cat unit-run.log

    - name: 'Upload Log Artifact'
      if: ${{ always() }}
      uses: actions/upload-artifact@v3
      with:
        name: unit-run.log
        path: unit-run.log
        retention-days: 5
